module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  roots: ["<rootDir>/src"],
  testMatch: ["**/__tests__/**/*.test.ts"],
  setupFilesAfterEnv: ["<rootDir>/src/__tests__/setup.ts"],
  collectCoverageFrom: [
    "src/**/*.ts",
    "!src/**/*.types.ts",
    "!src/index.ts",
    "!src/**/*.d.ts",
    "!src/scripts/**",
    "!src/routes/**",
    "!src/middlewares/autoLog.ts",
    "!src/middlewares/checkOrigin.ts",
    "!src/middlewares/notFoundMiddleware.ts",
    "!src/utils/limiter.ts",
    "!src/controllers/logController.ts",
  ],
  coverageThreshold: {
    global: {
      branches: 65,
      functions: 80,
      lines: 85,
      statements: 85,
    },
  },
  coverageDirectory: "coverage",
  verbose: true,
  forceExit: false,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
  detectOpenHandles: false,
  maxWorkers: 1,
};
