module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  roots: ["<rootDir>/src"],
  testMatch: ["**/__tests__/**/*.test.ts"],
  setupFilesAfterEnv: ["<rootDir>/src/__tests__/setup.ts"],
  setupFiles: ['./src/__tests__/helpers/setupEnv.ts'],
  moduleNameMapper: {
    '^.*/socket$': '<rootDir>/src/__tests__/__mocks__/socket.ts',
  },
  collectCoverageFrom: [
    "src/**/*.ts",
    "!src/__tests__/**",
    "!src/**/*.types.ts",
    "!src/index.ts",
    '!src/socket.ts',
    "!src/**/*.d.ts",
    "!src/scripts/**",
    "!src/routes/**",
    "!src/middlewares/autoLog.ts",
    "!src/middlewares/checkOrigin.ts",
    "!src/middlewares/notFoundMiddleware.ts",
    "!src/utils/limiter.ts",
    "!src/controllers/logController.ts",
  ],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 85,
      lines: 85,
      statements: 85,
    },
  },
  coverageDirectory: "coverage",
  verbose: true,
  forceExit: false,
  clearMocks: true,
  resetMocks: false,
  restoreMocks: false,
  detectOpenHandles: false,
  maxWorkers: 1,
};
